name: check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: nixbuild/nix-quick-install-action@5bb6a3b3abe66fd09bbf250dce8ada94f856a703 # v30
      - name: Check Nix formatting
        run: nix run nixpkgs#nixfmt-rfc-style -- --check **/*.nix

  check:
    runs-on: ${{ matrix.os }}
    needs: format
    permissions:
      contents: read
      actions: write
    
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, ubuntu-24.04-arm, macos-latest, macos-15-intel ]

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: nixbuild/nix-quick-install-action@5bb6a3b3abe66fd09bbf250dce8ada94f856a703 # v30
      - uses: nix-community/cache-nix-action@c448f065ba14308da81de769632ca67a3ce67cf5 # v6.1.2
        # FIXME: temporary workaround for https://github.com/actions/runner-images/issues/13341
        # Error: The template is not valid. .github/workflows/check.yaml (Line: 36, Col: 24):
        # hashFiles('flake.lock') failed. Fail to hash files under directory '/Users/runner/work/mcp-servers-nix/mcp-servers-nix'
        if: ${{ runner.os != 'macOS'}}
        with:
          primary-key: nix-${{ matrix.os }}-${{ hashFiles('flake.lock') }}
          restore-prefixes-first-match: nix-${{ matrix.os }}-
          purge: true
          purge-prefixes: nix-${{ matrix.os }}-
          purge-created: 0
      - name: Run nix flake check
        run: nix flake check --option keep-going true
